### ISSUE TITLE
Net::LDAP#add doesn't take Entry object

### ISSUE THREAD

**Issue by bg46z** [ruby-ldap/ruby-net-ldap#188]
Net::LDAP#add function doesn't take a well-formed Entry object as expected. Entry has no discernible way to go from an Entry object to an entry in the database.

**Comment by satoryu** [comment]
@bg46z could you tell us why you closed this issue if you're ok?

**Comment by bg46z** [comment]
Ticket has been open for a year, my patch didn't get very far. I haven't been following the project closely enough to tell if it was going to happen or not.

Best regards,
Zachary Bridges
