### ISSUE TITLE
Example works in IRB but not Rails Console

### ISSUE THREAD

**Issue by dmautz1** [ruby-ldap/ruby-net-ldap#192]
Maybe I'm doing something horribly wrong but if I run these same lines in irb and rails c, I get the following results:

require 'net/ldap'
ldap = Net::LDAP.new
ldap.host = "serverip"
ldap.port = 389
ldap.auth "username","password"
ldap.bind

In irb it returns "true"
In rails c it returns "Net::LDAP::LdapError: no connection to server"

In rails I have the gem 'ruby-net-ldap' in my gemfile. I created a brand new app using Rails 4.1.6 and Ruby 2.1.0. What in rails could be interfering with the connection?

**Comment by dmautz1** [comment]
Using devise + devise_ldap_authenticatable (https://github.com/cschiewek/devise_ldap_authenticatable), which also uses net-ldap, allows this example to return true in rails. I'm not sure how that gem is implementing it differently but it works for rails instances as opposed to the ruby-net-ldap gem.

**Comment by mtodd** [comment]
@dmautz1 https://rubygems.org/gems/ruby-net-ldap is not the same as https://rubygems.org/gems/net-ldap and is severely out of date. Use https://rubygems.org/gems/net-ldap in your gemfile: it's likely that devise_ldap_authenticatable loads the correct gem!
