### ISSUE TITLE
Enforcing Password History with MS AD

### ISSUE THREAD

**Issue by FreekingDean** [ruby-ldap/ruby-net-ldap#194]
net_ldap: 0.11
LDAP: Active Directory windows server 2012 r2

Currently I am attempting to run a modify command to change a users password via the current `modify()` method. It will work exactly as it should, though I need support to add a control specifically OID: '3.1.1.3.4.1.27' LDAP_SERVER_POLICY_HINTS_OID stated here: https://msdn.microsoft.com/en-us/library/hh128228.aspx

A real good addition (and this may already be available) would be to have the ability to define our own controls on `modify` `add` `delete` etc...

Let me know if any other info is necessary. I will also be attempting to add this on a fork!

This might be better labeled to say 'Allow `modify` to take controls as arguments.

**Comment by mtodd** [comment]
@FreekingDean any luck on a PR to add support for this?

**Comment by FreekingDean** [comment]
Unfortunately not, I thought I had added it, though I couldn't be sure it was being sent over. Either way it didn't work as intended. I think it might have been an MS/AD issue though. AD is very odd. I can hop back into buttoning the feature up on my side and writing some tests so I can do a PR.

Got busy with other LDAP issues :sos:

**Comment by FreekingDean** [comment]
I actually left my previous company that used ruby-ladp. I had tested it a few times and it did not work. I would chalk it up to oddities with different versions of ActiveDirectory. I am going to close this as I think it is unnecessary.
