### ISSUE TITLE
Referrals?

### ISSUE THREAD

**Issue by christopher-b** [ruby-ldap/ruby-net-ldap#206]
The History.rdoc file states that search referrals are support, but I can't find any documentation that explains how.

I'm running a search against ActiveDirectory. The search returns `nil`, and `get_operation_result` returns "Referral". How to I make the search resolve the referral? 

Thanks.

**Comment by mtodd** [comment]
@christopher-b there are [two options you can pass to the `search` method](https://github.com/ruby-ldap/ruby-net-ldap/blob/684431fbd658aa21593226fe5a525e8c65c856a6/lib/net/ldap/connection.rb#L400-L404) that you may be interested in: `:return_referrals` (boolean) and `:deref` (an [enum](https://github.com/ruby-ldap/ruby-net-ldap/blob/684431fbd658aa21593226fe5a525e8c65c856a6/lib/net/ldap.rb#L256-L259); see [docs](https://github.com/ruby-ldap/ruby-net-ldap/blob/684431fbd658aa21593226fe5a525e8c65c856a6/lib/net/ldap.rb#L698-L699)). Does that help?

To make this actionable: if that works as expected, do we need to clarify the docs further?

**Comment by christopher-b** [comment]
@mtodd Thanks for this info. I'm unable to test these options at this point, as our AD structure has changed (we're in the middle of restructuring). But I will know where to look for next time. 

I do think it would be useful to document the options that can be passed into #search. 

Thanks!
