### ISSUE TITLE
Access modifyTimestamp etc.

### ISSUE THREAD

**Issue by sonOfRa** [ruby-ldap/ruby-net-ldap#209]
OpenLDAP (not sure about other LDAP implementations) save some metadata in LDAP by default, for example modifyTimestamp, modifiersName, createTimestamp, creatorsName. Is it currently possible to access these with ``ldap.search()```? They don't seem to be returned by default. It'd be convienent to access these, especially for LDAP management tools, to gain some insight about who changed what (and when).

**Comment by sonOfRa** [comment]
Sorry for the noise, I misspelled them when I was trying to manually specify them in the attributes argument, and that's why they weren't showing up. They show up just fine when requesting them manually.

**Comment by jch** [comment]
Glad to hear it worked.
