### ISSUE TITLE
Where is the documentation? 

### ISSUE THREAD

**Issue by reiz** [ruby-ldap/ruby-net-ldap#215]
The README is almost empty. How do I implement an auth. against an LDAP server? Where are the code examples? Did I miss something?

**Comment by reiz** [comment]
Found it here: http://www.rubydoc.info/gems/ruby-net-ldap/Net/LDAP

**Comment by jch** [comment]
Thanks for opening this issue. We should update the gemspec so that it points to a valid documentation url.

**Comment by reiz** [comment]
:+1:
