### ISSUE TITLE
Start TLS error capitalization issue

### ISSUE THREAD

**Issue by justinoue** [ruby-ldap/ruby-net-ldap#233]
The class Net::LDAP::StartTLSError is defined here:
https://github.com/ruby-ldap/ruby-net-ldap/blob/4b22ea730293a49d096fc3cedc67a37bb8b48e37/lib/net/ldap/error.rb

But raised as Net::LDAP::StartTlSError here:
https://github.com/ruby-ldap/ruby-net-ldap/blob/4b22ea730293a49d096fc3cedc67a37bb8b48e37/lib/net/ldap/connection.rb

Someone didn't capitalize the L in TLS.

**Comment by satoryu** [comment]
This bug has been fixed by #234 so we can close this issue.  @justinoue @jch
