### ISSUE TITLE
Provide test coverage at integration level for network errors

### ISSUE THREAD

**Issue by astratto** [ruby-ldap/ruby-net-ldap#244]
We should have integration tests to cover connection failures/timeouts.

One possible approach is to use iptables to drop/reject packets.

For instance, to test that a socket connect timeout is triggered, something like
```iptables -A OUTPUT -p tcp -j DROP --dport 389``` can be used.

We should investigate how to play with this on Travis.

**Comment by jch** [comment]
> We should investigate how to play with this on Travis.

:+1:
