### ISSUE TITLE
Encryption Bug

### ISSUE THREAD

**Issue by tonobo** [ruby-ldap/ruby-net-ldap#250]
Hey, 0.12.1 is incompatible with 0.13.0.  I get the following trace, with encryption enabled.

"no implicit conversion of Symbol into Integer"

net-ldap (0.13.0) lib/net/ldap/connection.rb:118:in `[]'
net-ldap (0.13.0) lib/net/ldap/connection.rb:118:in`setup_encryption'
net-ldap (0.13.0) lib/net/ldap/connection.rb:30:in `prepare_socket'
net-ldap (0.13.0) lib/net/ldap/connection.rb:44:in`block in open_connection'
net-ldap (0.13.0) lib/net/ldap/connection.rb:42:in `each'
net-ldap (0.13.0) lib/net/ldap/connection.rb:42:in`open_connection'
net-ldap (0.13.0) lib/net/ldap/connection.rb:19:in `initialize'
net-ldap (0.13.0) lib/net/ldap.rb:1254:in`new'
net-ldap (0.13.0) lib/net/ldap.rb:1254:in `new_connection'
net-ldap (0.13.0) lib/net/ldap.rb:849:in`block in bind'
net-ldap (0.13.0) lib/net/ldap/instrumentation.rb:19:in `instrument'
net-ldap (0.13.0) lib/net/ldap.rb:843:in`bind'

**Comment by jch** [comment]
@timmyArch could you include the snippet of code you're calling with?

**Comment by timmyArch** [comment]
@jch this will do the trick ;)

ldap = Net::LDAP.new(
      :host => LDAP_HOST,
      :port => LDAP_PORT,
      :base => LDAP_BASE,
      :encryption => :simple_tls,
      :auth => { :method => :simple, :username => user_dn, :password => password }
    )
ldap.bind

**Comment by jch** [comment]
@timmyArch The constructor way of initializing encryption requires a hash (https://github.com/ruby-ldap/ruby-net-ldap/pull/239). This is different than old way of setting it through the `#encryption` method, but it does standardize the param. Your example should work with:

```ruby
ldap = Net::LDAP.new(:encryption => { :simple_tls }, ...)
ldap.bind
```

@satoryu I noticed the "Documentation" link on https://rubygems.org/gems/net-ldap/versions/0.13.0 links to a really old version of net-ldap (0.0.4). I tried to file a bug on rubydoc.info, but got a 500. Any ideas?

**Comment by timmyArch** [comment]
@jch encryption accepts an array? Are there multiple types of encryption?

**Comment by jch** [comment]
@timmyArch there are, docs are unfortunately linking to the wrong version, but you can see it in the source here: https://github.com/ruby-ldap/ruby-net-ldap/blob/b32f4e774bcf15d243f2f7b58b38919e789cde5a/lib/net/ldap.rb#L479-L505

**Comment by satoryu** [comment]
@jch the current link is for ruby-net-ldap not net-ldap. replace it with http://www.rubydoc.info/gems/net-ldap/Net/LDAP .

**Comment by jch** [comment]
@satoryu thanks. It's closer at 0.12.1, but still not quite there.

**Comment by timmyArch** [comment]
Ah nice thanks, this will help. But it will be fine to get a pre parameter validation. To prevent such fails. Normally it should be always backwards compatible after minor Version bump.

**Comment by christopher-b** [comment]
To clarify @jch's example above, either of these should work:

```ruby
ldap = Net::LDAP.new(:encryption => { :method => :simple_tls }, ...)
ldap = Net::LDAP.new(:encryption => [ :simple_tls ], ...)
```

**Comment by jch** [comment]
> But it will be fine to get a pre parameter validation. To prevent such fails.

@satoryu would you be interested in adding a check and raising ArgumentError if someone passes in a non-hash?

> Normally it should be always backwards compatible after minor Version bump.

@timmyArch I agree with you that this was confusing behavior to a user, but this is actually a new interface so there is no backwards compatibility to consider. The old way of setting encryption was to set it after initialization:

```ruby
ldap = Net::LDAP.new(...)
ldap.encryption(...)
```

This makes me want to revisit releasing a major version so we can have more stability in the API since there are many production environments that rely on this gem. I'll open up a separate issue for that.

**Comment by satoryu** [comment]
:ok_hand: I'll sent a PR.

**Comment by cthielen** [comment]
I want to second this API breakage lament.

We use net-ldap heavily in production and also have been passing encryption as a simple symbol, not a hash, and ended up with minor production downtime.

**Comment by jch** [comment]
@cthielen Thanks for reporting in.

How did you previously set up encryption? This introduces a new way of setting encryption through the constructor, which was not previously available. If you set it up via `#encryption`, the API is deprecated, but continues to work as previously. There shouldn't be an API breakage.

**Comment by sgringwe** [comment]
Also was affected by this with same configuration as @timmyArch. We mock most of our ldap code in tests so we didn't catch it.

Regardless @jch, not too big of a deal and I appreciate the time you spend on this library!

**Comment by ryanshow** [comment]
@jch the Net::LDAP constructor has accepted an :encryption parameter since at least v0.2, see here:

https://github.com/ruby-ldap/ruby-net-ldap/blob/v0.2/lib/net/ldap.rb#L382

It was modified in def2c463d4cea77a5e6d40690def1b2a9a8a8f7f to accept a different type of parameter, thus breaking the existing API.

**Comment by jch** [comment]
@ryanshow @cthielen I'm sorry, I must've missed that during code review. I believe @satoryu expressed interest in working on this, but would either of you be interested in opening a PR to remedy this?

**Comment by jch** [comment]
v0.14.0 should fix this https://github.com/ruby-ldap/ruby-net-ldap/pull/265

**Comment by satoryu** [comment]
@ryanshow @timmyArch @cthielen I'm sorry. As @ryanshow 's work #264 , you would be able to specify encryption method as Symbol. 

@jch I was working on implementing a validation for `encryption` option. I think it is not needed since normalization has been adopted. what do you think?

**Comment by timmyArch** [comment]
@satoryu Thanks a lot! :+1:

@jch, @satoryu The greatest way *in my opinion* would be the implement a generic parameter validation.
