### ISSUE TITLE
Ldap search returns "blank" entries, with DN as the single attribute

### ISSUE THREAD

**Issue by zeroalpha** [ruby-ldap/ruby-net-ldap#263]
First of, my setup is as following.

i am using ruby 2.1.4p265 on Windows 7 x64 and net-ldap 0.13.0
The LDAP Server i am trying to query is an z/OS Integradet Security LDAP Server version 4.1

I have the following ruby code which runs without any Exceptions.

```ruby
ldap = Net::LDAP.new
ldap.host = 'host'
ldap.port = 389 #Port
ldap.auth 'racfid=REDACTED,profiletype=USER,sysplex=TESTPLEX', 'REDACTED'

if ldap.bind then
  filter = Net::LDAP::Filter.eq('racfid','REDACTED')
  group_entry = ldap.search({
    base: 'profiletype=GROUP,sysplex=TESTPLEX',
    filter: filter
    #attributes_only: true
    #attributes: %w{racfid racfgroupuserids}
  })
  binding.pry
  puts "YAY"
else
  puts "NAY"
end
```

But the returned entry has only a single attribute, its DN
```
#<Net::LDAP::Entry:0x000000045d4680
 @myhash={:dn=>["racfid=REDACTED,profiletype=USER,sysplex=testplex"]}>
```

Using a LDAP Browser like ldapadmin i can verify that there are far more attributes on an entry.
I also tried, setting attributes_only to true or specifying the attributes i need, but to no avail.

Whilst i could just fallback to using ldapsearch an parsing the results, I feel like this could be an actual Bug affecting more people.

**Comment by zeroalpha** [comment]
It turns out, that this is working as designed (by IBM).
The filter and base of the search operation determine whether a full entry or an "DN-Only" Entry is returned.

I am sorry for any inconvenience

**Comment by jch** [comment]
@zeroalpha thanks for reporting this. It'll be helpful for others searching on a similar issue.
