### ISSUE TITLE
Undefined method `ord` for nil class

### ISSUE THREAD

**Issue by dasomx77** [ruby-ldap/ruby-net-ldap#266]
Hey there, 
I am currently seeing intermittent issues with this gem; every once a while, our connection with ldap will drop and fail with this backtrace:
"/opt/shared/bundle/ruby/2.2.0/gems/net-ldap-0.11/lib/net/ldap/connection.rb:33:in `getbyte'", "/opt/shared/bundle/ruby/2.2.0/gems/net-ldap-0.11/lib/net/ber/ber_parser.rb:169:in`read_ber'", "/opt/shared/bundle/ruby/2.2.0/gems/net-ldap-0.11/lib/net/ldap/connection.rb:178:in `block in read'", "/opt/shared/bundle/ruby/2.2.0/gems/net-ldap-0.11/lib/net/ldap/instrumentation.rb:19:in`instrument'", "/opt/shared/bundle/ruby/2.2.0/gems/net-ldap-0.11/lib/net/ldap/connection.rb:177:in `read'", "/opt/shared/bundle/ruby/2.2.0/gems/net-ldap-0.11/lib/net/ldap/connection.rb:143:in`queued_read'", "/opt/shared/bundle/ruby/2.2.0/gems/net-ldap-0.11/lib/net/ldap/connection.rb:253:in `bind_simple'", "/opt/shared/bundle/ruby/2.2.0/gems/net-ldap-0.11/lib/net/ldap/connection.rb:222:in`block in bind'", "/opt/shared/bundle/ruby/2.2.0/gems/net-ldap-0.11/lib/net/ldap/instrumentation.rb:19:in `instrument'", "/opt/shared/bundle/ruby/2.2.0/gems/net-ldap-0.11/lib/net/ldap/connection.rb:219:in`bind'"

As far as I can tell, this works flawlessly most of the time since I have a couple of cron jobs that reuse the same piece of code over and over again and this only happens (very consistently) every week or may be a bit more frequently than that. The steps to reproduce this issue are literally attempting to bind. I am tempted to say perhaps that when the connection times out, either a nil object is returned to the calling function which then attempts to send it the ord command which then fails, but again, I haven't taken a look at the source code as of now.

**Comment by dasomx77** [comment]
Bump? Anyone aware of what could be triggering this?

**Comment by mynameisrufus** [comment]
This code has changed in master https://github.com/ruby-ldap/ruby-net-ldap/blob/master/lib/net/ldap/connection.rb#L33 might be worth upgrading and see if issue persists.

**Comment by tmccombs** [comment]
So, I think what is happening, is that `getc` returns nil at end of file, but that causes `getbyte` to raise an error.

**Comment by HarlemSquirrel** [comment]
Should be fixed by #306
