### ISSUE TITLE
Show operational attributes

### ISSUE THREAD

**Issue by kees24** [ruby-ldap/ruby-net-ldap#275]
**How do I get operational attributes listed as an entry?** 

By default the output doesn't contain this data. When you are using ldapsearch you can specify "+" at the end to show also operational attributes.

I can't find an option to make this possible but there must be way. Mainly because you can successfully filter for them. For example "Net::LDAP::Filter.present("pwdAccountLockedTime")" just works.

Hopefully someone can show me how it's done.

Thanks in advance.

Note:
pwdAccountLockedTime is an operational attibutes and belongs to the PPolicy overlay.

**Comment by aschubert** [comment]
**It's already possible**

Hi, just tried it by myself. It's possible, like you would do it in ldapsearch. Just do a search like

`result = ldap.search(:base => ... , :filter => ... , :attributes => ['*','+'])`

The key point is the `:attributes`-Array, it must contain `+` for operational attributes (the `*` in the example additionally shows all other attributes).
