### ISSUE TITLE
how to add an entry to openldap with password?

### ISSUE THREAD

**Issue by wangchuande** [ruby-ldap/ruby-net-ldap#282]
how to add an entry to openldap with password?

**Comment by satoryu** [comment]
Hoping the following documents would help you:

* http://www.rubydoc.info/gems/net-ldap/Net/LDAP#open-class_method
* http://www.rubydoc.info/gems/net-ldap/Net%2FLDAP%3Aadd

**Comment by wangchuande** [comment]
@satoryu Thanks, I found the solution, and this is my code.
`ldap = Net::LDAP.new
ldap.host = "127.0.0.1"
ldap.auth "cn=admin,dc=example,dc=com", '123456'

password = Net::LDAP::Password.generate(:md5, '123456')
dn = "cn=test,dc=example,dc=com"
attr = {
  cn: "test",
  objectclass: ["top", "person"],
  sn: "chuande",
  userPassword: password
 }

ldap.add(dn: dn, attributes: attr)`

I didn't success before, because I found the password attribute value is "Password"  through phpldapadmin, but accutually the password attibute value is "userPassword" in openLDAP.
