### ISSUE TITLE
`Net::LDAP::DN` should raise an error more specific than `RuntimeError`

### ISSUE THREAD

**Issue by dblessing** [ruby-ldap/ruby-net-ldap#283]
Currently, `Net::LDAP::DN` raises `RuntimeError` in certain conditions. This is a very non-specific errors and makes it hard to catch LDAP exceptions without accidentally catching a more generic runtime error. 

Can we add more specific error classes for these cases?

**Comment by satoryu** [comment]
Could you give us more information to reproduce your situation, the version of net-ldap and actual stack traces etc.?

**Comment by dblessing** [comment]
Everywhere in https://github.com/ruby-ldap/ruby-net-ldap/blob/master/lib/net/ldap/dn.rb where the code says `raise "message"` is raising a RuntimeError rather than a specific `Net::LDAP` error. There's also an acknowledgement in the tests that this is not the best - https://github.com/ruby-ldap/ruby-net-ldap/blob/master/test/test_dn.rb#L29
