### ISSUE TITLE
Simplistic modify call fails with undefined method `to_ber_enumerated'

### ISSUE THREAD

**Issue by jblaine** [ruby-ldap/ruby-net-ldap#290]
The following code using net-ldap-0.16.0:
```
    @ldapconn.modify({
      :dn         => "cn=testnetgroup,ou=Netgroup,dc=example,dc=com",
      :operations => [:delete, 'nisNetgroupTriple', "(-,testuser,)"]
    })
```
results in:
```
/home/jblaine/src/rcf-accounts/vendor/bundle/ruby/2.3.0/gems/net-ldap-0.16.0/lib/net/ldap/connection.rb:534:in `block in modify_ops': undefined method `to_ber_enumerated' for nil:NilClass (NoMethodError)
        from /home/jblaine/src/rcf-accounts/vendor/bundle/ruby/2.3.0/gems/net-ldap-0.16.0/lib/net/ldap/connection.rb:531:in `each'
        from /home/jblaine/src/rcf-accounts/vendor/bundle/ruby/2.3.0/gems/net-ldap-0.16.0/lib/net/ldap/connection.rb:531:in `modify_ops'
        from /home/jblaine/src/rcf-accounts/vendor/bundle/ruby/2.3.0/gems/net-ldap-0.16.0/lib/net/ldap/connection.rb:552:in `modify'
        from /home/jblaine/src/rcf-accounts/vendor/bundle/ruby/2.3.0/gems/net-ldap-0.16.0/lib/net/ldap.rb:1055:in `block (2 levels) in modify'
        from /home/jblaine/src/rcf-accounts/vendor/bundle/ruby/2.3.0/gems/net-ldap-0.16.0/lib/net/ldap.rb:1303:in `use_connection'
        from /home/jblaine/src/rcf-accounts/vendor/bundle/ruby/2.3.0/gems/net-ldap-0.16.0/lib/net/ldap.rb:1054:in `block in modify'
        from /home/jblaine/src/rcf-accounts/vendor/bundle/ruby/2.3.0/gems/net-ldap-0.16.0/lib/net/ldap/instrumentation.rb:19:in `instrument'
        from /home/jblaine/src/rcf-accounts/vendor/bundle/ruby/2.3.0/gems/net-ldap-0.16.0/lib/net/ldap.rb:1053:in `modify'
        from rcf_user.rb:93:in `remove_from_netgroup'
        from rcf_user.rb:115:in `<main>'
```
Any thoughts would be appreciated, as I don't see anything I am doing wrong. Everything else (so far), which amounts to `bind` and `replace_attribute`, works fine.

**Comment by jaapie** [comment]
I'm interested to know if you came up with a fix or work-around for this.

**Comment by jblaine** [comment]
@jaapie No fix or work-around. Our project stalled for now :(

**Comment by jaapie** [comment]
I figured out mine was an error in my code so my issue was sorted. Sorry. I hope you find a fix soon.

**Comment by jblaine** [comment]
Forgot about this and then hit this same problem again with different DN targeted ("Ohhhh yeahhhh.... this problem again."). Mentioning it only to point out that the problem is not specific to the previously reported DN or part of the LDAP DIT.
```
        @ldapconn.modify({
            :dn         => "cn=mygroup,ou=Group,dc=example,dc=com",
            :operations => [:delete, 'memberUid', 'jblaine']
        })
```

**Comment by chuvi** [comment]
Hello!
I've been struggling with that error for days, so I gave up the method @ldapconn.modify and tried to use @ldapconn.replace_attribute  instead. Additionally, I had to change permission level for the binding user.

This code has worked gracefully to me:

        filter1 = Net::LDAP::Filter.eq("sAMAccountName",person.username)
        a = ldap.search(
            :base => "ou=XXX,dc=YYY,dc=ZZZ",
            :filter => filter1 
            )
         dn = a.first.dn
      
        ldap.replace_attribute dn, 'extensionAttribute1', value_of_the_attribute

**Comment by agouaux** [comment]
Oh bummer.  I hit this too, and sad to hear that this project is stalled.

**Comment by CDeighton** [comment]
Just ran into this - the operations arg seems to expect a double array so it can run multiple modifies. So:

```
 @ldapconn.modify({
      :dn         => DN,
      :operations => [ [:delete, ATTR, VALUE] ]
    })
```

Fixed it for me. Hope that helps

**Comment by jblaine** [comment]
> Oh bummer. I hit this too, and sad to hear that this project is stalled.

@agouaux I was replying above with "Our project stalled for now :(" to another person here as a **user** of this code, not as a **maintainer**. I am not making any comment about the state of the ruby-net-ldap project.

@CDeighton Pending confirmation that it works for us as well, you may be my hero this month.

**Comment by jblaine** [comment]
> 
> 
> Just ran into this - the operations arg seems to expect a double array so it can run multiple modifies. So:
> 
> ```
>  @ldapconn.modify({
>       :dn         => DN,
>       :operations => [ [:delete, ATTR, VALUE] ]
>     })
> ```
> 
> Fixed it for me. Hope that helps

Yes! This worked. Thank you for taking the time to reply here with your finding, @CDeighton
