### ISSUE TITLE
Storing salt alongside with salted password

### ISSUE THREAD

**Issue by amocrenco** [ruby-ldap/ruby-net-ldap#295]
https://github.com/ruby-ldap/ruby-net-ldap/blob/78e97ed69dc9ebbf06b04e7e70ceb046c23de75c/lib/net/ldap/password.rb#L31

Could you please explain me what is the point of using salt if it is stored in cleartext?

This will protect from rainbow tables, but will be useless during bruteforce attacks, because salt becomes known to the attacker by just base64 decoding the string.

Right?

**Comment by mkozono** [comment]
I think you've got it, although it is useful during bruteforce attacks on groups of salted passwords, right? I don't know the context of where this is used.

And I think salt is commonly stored in cleartext.

**Comment by amocrenco** [comment]
Thanks!
