### ISSUE TITLE
Are there any active maintainers still present here?

### ISSUE THREAD

**Issue by clader** [ruby-ldap/ruby-net-ldap#316]
There seems to only have been one merged PR in the last 18+ months, and little or no replies on the issue board or open PR's.  

Our company uses this gem heavily and I'd hate for this project to have gone completely dark.

**Comment by schaary** [comment]
Yes - I am still there, but I am not active anymore. We use this gem heavily as well - but I since more than a year I write only Elixir for our backend. 

Are you interested in becoming a maintainer?

**Comment by HarlemSquirrel** [comment]
My organization uses this gem quite a bit and I would be happy to help out as a maintainer.

**Comment by HarlemSquirrel** [comment]
@mtodd any interest in an additional maintainer?

**Comment by HarlemSquirrel** [comment]
@schaary @jch @mtodd 
I'm still happy to help out as an additional maintainer.
