### ISSUE TITLE
Can we release a new version to ruby gems? 

### ISSUE THREAD

**Issue by Sarin1204** [ruby-ldap/ruby-net-ldap#323]
The last version was in October 2017. It would be nice to have the fix in https://github.com/ruby-ldap/ruby-net-ldap/pull/308

**Comment by satoryu** [comment]
@schaary @mtodd @jch do you have any plan to release new version?

**Comment by jch** [comment]
I'm sorry, but I'm no longer a maintainer on the project and do not have access.

**Comment by jethrodaniel** [comment]
See https://github.com/ruby-ldap/ruby-net-ldap/pull/335

**Comment by mtodd** [comment]
Thanks for referencing #335 @jethrodaniel! Yes, indeed, the latest release will include #308. Apologies for the delay in releases.
