### ISSUE TITLE
Compatibility with Ruby 2.7?

### ISSUE THREAD

**Issue by pedrofurtado** [ruby-ldap/ruby-net-ldap#341]
There is a warning running the gem with ruby 2.7:

```bash
/usr/local/rvm/gems/ruby-2.7.0@myapp/gems/net-ldap-0.16.2/lib/net/ldap/connection.rb:713: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
```

**Comment by pedrofurtado** [comment]
Is there some planning to release a version with this fix? @HarlemSquirrel

**Comment by HarlemSquirrel** [comment]
@pedrofurtado I do not currently have the ability to push a gem release to RubyGems. Those folks are listed at https://rubygems.org/gems/net-ldap

**Comment by pedrofurtado** [comment]
@schaary @mtodd 🤝
