### ISSUE TITLE
CI: JRuby builds fail

### ISSUE THREAD

**Issue by olleolleolle** [ruby-ldap/ruby-net-ldap#361]
This Issue is about the CI build failures on JRuby.

## Issues noted

- [ ] the `jruby-19mode` installs JRuby 9.2.5.0, which represents... what, really? (`Found remote file https://repo1.maven.org/maven2/org/jruby/jruby-dist/9.2.5.0/jruby-dist-9.2.5.0-bin.tar.gz`). The last 1.9 would be `jruby-1.7.27`, but his is long out of support.
- [ ] Fails on installing byebug C extension
- [ ] JRuby 9.2.12.0 has fixed all the Illegal Access module issues, according to its [latest blog post about that release](https://www.jruby.org/2020/07/01/jruby-9-2-12-0.html).

**Comment by HarlemSquirrel** [comment]
Thanks for reporting! These are all fixed now with #363 and #365
