### ISSUE TITLE
RubyDoc documentation unavailable

### ISSUE THREAD

**Issue by ceicke** [ruby-ldap/ruby-net-ldap#384]
Hello,

the reference to the RubyDoc documentation (https://www.rubydoc.info/gems/net-ldap/Net/LDAP) is not working. I don't know if this is an issue on RubyDoc's side or if it's an issue that can be solved here.

**Comment by esparta** [comment]
I just added the repo to the index, so it's not live on RubyDoc, so this can be closed :)
