### ISSUE TITLE
Please make a new release

### ISSUE THREAD

**Issue by rjschof** [ruby-ldap/ruby-net-ldap#402]
There have been multiple updates to this repository since Release 0.17.0. We cannot access any of those updates via Rubygems since there has not been a new release since 2020. 

Pointing our Gemfile to `ruby-net-ldap@master` is not a good enough solution. Please cut a new release and push it to Rubygems.

**Comment by HarlemSquirrel** [comment]
@rjschof I haven't been getting notifications for this repository and don't currently work on any projects using this library anymore so it's fallen off my radar. 

I did start a PR for the next release.

**Comment by rjschof** [comment]
@HarlemSquirrel Thank you!
